import React from 'react'

export default {
  intro: '',
  me: '',
  roadmap: '',
  wontTalkAbout: '',
  willTalkAbout: '',
  fp: '',
  iKnowFP: '',
  definition: '',
  functions: '',
  hofs: '',
  hofsCode: '',
  pureFunctions: '',
  pureFunctionsDefinition: '',
  pureFunctionsCode: '',
  ezTestEsLife: '',
  ezTestEsLifeCode: '',
  pureExample: '',
  composition: '',
  compositionCode: '',
  fractal: '',
  compositionVsInheritance: '',
  inheritanceCode: '',
  compositionCode: '',
  curry: '',
  curryCode: '',
  declarative: '',
  declarativeCode: '',
  immutability: '',
  immutabilityPros: '',
  immutabilityResources: '',
  immutabilityCode: '',
  whyTho: '',
  becauseJS: '',
  becauseWeCan: '',
  resources: '',
  libraries: '',
  learning: '',
  more: '',
  questions: '',
  remember: '',
}
